//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("PSMultiTools.Core")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+401f9719546d7c932e4d662cfdf0fe6639e4de9a")]
[assembly: System.Reflection.AssemblyProductAttribute("PSMultiTools.Core")]
[assembly: System.Reflection.AssemblyTitleAttribute("PSMultiTools.Core")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Von der MSBuild WriteCodeFragment-Klasse generiert.

